### ISSUE TITLE
Building pmac-utils

### ISSUE THREAD

**Issue by Wooty-B** [r-c-f/pmac-utils#1]
First off thanks for keeping this utility alive and realizing it's need, and as you probably know trying to install Debian sid results in a dependency loop hell. I'll go ahead and give a brief description of what I am currently running into for context.

I have a PowerMac G5 Quad and have watched several videos and guides of users earlier this year installing Debian sid with no issues. However, when I attempt to use the NETINSTALL Debian iso's or build the drive with debootstrap, I am plagued by powerpc-utils not being able to be installed because of the missing pmac-utils package.

I've been fumbling around for days and came across this repository, which seems to be the solution to this issue. I am using a recent install of Void Linux to tackle this and was wondering how I would compile this package for my system? I am used to using make/cmake out of the box and not quite sure how to proceed. Any information to help me build this for my system would be wonderful. Thanks again!

**Comment by r-c-f** [comment]
Unfortunately I've never actually used this with Debian, only Void. However, it should be sufficient to use a Debian chroot (which should be possible to construct without pmac-utils) and run [debuild](https://manpages.debian.org/stretch/devscripts/debuild.1.en.html) using the files in the `debian` directory of this repo.

**Comment by Wooty-B** [comment]
@r-c-f That solution worked for me, thank you!
